/**
 * 入站邮件规范化：mailparser 产物 → EmailInboundEvent。
 * 处理自动回复环防护、大小限制、文本/HTML 裁剪、线程引用链提取。
 */
import { simpleParser, type ParsedMail } from "mailparser";
import {
  EMAIL_ATTACHMENT_LIMIT_BYTES, EMAIL_BODY_LIMIT_CHARS, EMAIL_MESSAGE_LIMIT_BYTES,
  EMAIL_SUBJECT_LIMIT_CHARS, isAutoGenerated, type EmailInboundEvent,
} from "./email-types.js";

export interface NormalizeEmailOptions {
  /** 源数据总字节数上限（超限直接拒绝入站） */
  messageLimitBytes?: number;
  attachmentLimitBytes?: number;
  now?: () => Date;
}

function cleanText(value: string | undefined | null): string {
  const text = String(value ?? "").replace(/\r\n?/g, "\n");
  return text.length > EMAIL_BODY_LIMIT_CHARS ? text.slice(0, EMAIL_BODY_LIMIT_CHARS) : text;
}

function subjectOf(mail: ParsedMail): string {
  const subject = String(mail.subject ?? "").replace(/\s+/g, " ").trim();
  return subject.length > EMAIL_SUBJECT_LIMIT_CHARS ? subject.slice(0, EMAIL_SUBJECT_LIMIT_CHARS) : subject;
}

function referencesOf(mail: ParsedMail): { messageId: string; references: string[]; threadId: string } {
  const strip = (value: string) => value.trim().replace(/^<|>$/g, "");
  const messageId = strip(String(mail.messageId ?? ""));
  const inReplyTo = strip(String(mail.inReplyTo ?? "").split(/\s+/).at(-1) ?? "");
  const parsed = Array.isArray(mail.references) ? mail.references : String(mail.references ?? "").split(/\s+/).filter(Boolean);
  const references = parsed.map(strip).filter(Boolean);
  if (inReplyTo && !references.includes(inReplyTo)) references.push(inReplyTo);
  const threadId = references[0] ?? messageId;
  if (messageId && !references.includes(messageId)) references.push(messageId);
  return { messageId, references: references.length ? references : (messageId ? [messageId] : []), threadId };
}

/**
 * 原始邮件字节流 → 规范化入站事件。
 * 返回 null 表示该邮件不应进入 Agent（自动回复环、超限、无 Message-ID）。
 */
export async function normalizeEmail(raw: Buffer | string, options: NormalizeEmailOptions = {}): Promise<EmailInboundEvent | null> {
  const messageLimit = options.messageLimitBytes ?? EMAIL_MESSAGE_LIMIT_BYTES;
  const buffer = Buffer.isBuffer(raw) ? raw : Buffer.from(raw);
  if (buffer.byteLength > messageLimit) return null;

  const mail = await simpleParser(buffer, {
    skipHtmlToText: false,
    skipTextToHtml: false,
    skipImageLinks: true,
    maxHtmlLengthToParse: 500_000,
  });
  if (isAutoGenerated(mail.headers?.get("auto-submitted") as string | undefined)) return null;

  const { messageId, references, threadId } = referencesOf(mail);
  if (!messageId) return null;

  const fromEntry = Array.isArray(mail.from) ? mail.from[0] : mail.from;
  const fromList = fromEntry ? (Array.isArray(fromEntry.value) ? fromEntry.value : [fromEntry.value]) : [];
  const from = fromList[0] ?? {};
  const senderAddress = String((from as { address?: string }).address ?? "");
  if (!senderAddress) return null;

  const toEntry = Array.isArray(mail.to) ? mail.to[0] : mail.to;
  const toList = toEntry ? (Array.isArray(toEntry.value) ? toEntry.value : [toEntry.value]) : [];
  const toAddresses = toList.map((entry: { address?: string }) => String(entry.address ?? "")).filter(Boolean);

  const attachments = (mail.attachments ?? [])
    .filter((attachment: { size?: number }) => (attachment.size ?? 0) <= (options.attachmentLimitBytes ?? EMAIL_ATTACHMENT_LIMIT_BYTES))
    .map((attachment: { filename?: string | false; contentType?: string; size?: number }) => ({
      filename: String(attachment.filename ?? "").slice(0, 255),
      contentType: String(attachment.contentType ?? "application/octet-stream"),
      size: attachment.size ?? 0,
    }));

  return {
    messageId,
    threadId,
    references,
    sender: {
      name: String((from as { name?: string }).name ?? "").replace(/\s+/g, " ").trim().slice(0, 200),
      address: senderAddress,
    },
    toAddresses,
    subject: subjectOf(mail),
    textBody: cleanText(mail.text),
    htmlBody: mail.html ? cleanText(mail.html).slice(0, EMAIL_BODY_LIMIT_CHARS) : null,
    attachments,
    autoGenerated: false,
    receivedAt: (options.now ?? (() => new Date()))().toISOString(),
  };
}
