/**
 * Agent Email Phase 1（issue #93）共享类型。
 * 通用性设计：收信 IMAP、发信 SMTP 是所有邮箱服务商的协议公约数；
 * 入站信封与 Feishu IM 入站共用同一 deliver/wake 管线语义。
 */

export interface EmailAccountConfig {
  /** bot 自己的邮箱地址（收件人判定与发件人 From） */
  address: string;
  imap: {
    host: string;
    port: number;
    tls: boolean;
    /** 用户名（通常为完整邮箱地址） */
    user: string;
    /** 密码或授权码（腾讯/Gmail 等要求授权码） */
    password: string;
  };
  smtp: {
    host: string;
    port: number;
    tls: boolean;
    user: string;
    password: string;
  };
}

export interface EmailAttachment {
  filename: string;
  contentType: string;
  size: number;
}

export interface EmailInboundEvent {
  /** RFC 5322 Message-ID（无尖括号） */
  messageId: string;
  /** 线程根：取 References 链首项，其次 In-Reply-To，否则自身 messageId */
  threadId: string;
  /** 完整 References 链（含自身，用于回复头） */
  references: string[];
  sender: { name: string; address: string };
  toAddresses: string[];
  subject: string;
  textBody: string;
  htmlBody: string | null;
  attachments: EmailAttachment[];
  /** 自动回复/退信等不应唤醒 Agent 的邮件 */
  autoGenerated: boolean;
  receivedAt: string;
}

export interface EmailThreadRefs {
  messageId: string;
  references: string[];
}

export const EMAIL_BODY_LIMIT_CHARS = 120_000;
export const EMAIL_SUBJECT_LIMIT_CHARS = 500;
export const EMAIL_ATTACHMENT_LIMIT_BYTES = 10 * 1024 * 1024;
export const EMAIL_MESSAGE_LIMIT_BYTES = 25 * 1024 * 1024;

/** RFC 规范要求收件人忽略 Auto-Submitted 为 auto-replied/auto-generated 的邮件回复 */
export function isAutoGenerated(autoSubmitted: string | undefined): boolean {
  const value = String(autoSubmitted || "").toLocaleLowerCase("en-US").replace(/\s+/g, " ");
  return value === "auto-replied" || value === "auto-generated"
    || /^auto-(replied|generated)\b/.test(value);
}

export function validEmailAddress(value: string): boolean {
  return /^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value.trim()) && !/[\r\n]/.test(value);
}
