/**
 * IMAP 收件源（Phase 1）：imapflow + IDLE 长连接推送，断线回落到轮询，
 * UIDVALIDITY/UIDNEXT 持久化追踪保证不重不漏。
 */
import { ImapFlow, type FetchMessageObject, type MailboxObject } from "imapflow";
import { normalizeEmail } from "./email-normalize.js";
import { isAutoGenerated, type EmailAccountConfig, type EmailInboundEvent } from "./email-types.js";

export interface ImapStateStore {
  read(): { uidValidity: string | null; lastUid: number };
  write(value: { uidValidity: string | null; lastUid: number }): void;
}

export interface ImapSourceOptions {
  account: EmailAccountConfig;
  store: ImapStateStore;
  onMessage(event: EmailInboundEvent): void | Promise<void>;
  onError?(error: Error): void;
  log?: (...parts: unknown[]) => void;
  idlePollFallbackMs?: number;
  now?: () => Date;
  createClient?: (config: EmailAccountConfig) => ImapFlow;
}

export interface ImapSource {
  start(): Promise<void>;
  stop(): Promise<void>;
  /** 立即执行一次轮询（测试与外部触发用） */
  pollOnce(): Promise<number>;
}

export function createImapSource(options: ImapSourceOptions): ImapSource {
  const log = options.log ?? (() => {});
  const idlePollFallbackMs = options.idlePollFallbackMs ?? 60_000;
  const createClient = options.createClient ?? ((account) => new ImapFlow({
    host: account.imap.host,
    port: account.imap.port,
    secure: account.imap.tls,
    auth: { user: account.imap.user, pass: account.imap.password },
    logger: false,
    emitLogs: false,
  }));

  let client: ImapFlow | null = null;
  let stopped = false;
  let reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  let openedMailbox: MailboxObject | null = null;

  const state = () => options.store.read();

  const deliverNew = async (): Promise<number> => {
    if (!client || !openedMailbox) return 0;
    const lock = await client.getMailboxLock("INBOX");
    let delivered = 0;
    try {
      const mailbox = openedMailbox;
      const { uidValidity, lastUid } = state();
      if (uidValidity !== null && String(mailbox.uidValidity) !== uidValidity) {
        // UIDVALIDITY 变化：UID 全部失效，从头扫描（防止旧状态造成漏信）。
        options.store.write({ uidValidity: String(mailbox.uidValidity), lastUid: 0 });
      }
      const fromUid = state().lastUid + 1;
      if (fromUid > (mailbox.uidNext ?? fromUid)) return 0;
      for await (const message of client.fetch(`${fromUid}:*`, { uid: true, source: true }, { uid: true })) {
        if (stopped) break;
        try {
          const raw = Buffer.isBuffer(message.source) ? message.source : Buffer.from(String(message.source ?? ""));
          const event = await normalizeEmail(raw, { now: options.now });
          if (!event) continue;
          await options.onMessage(event);
          delivered += 1;
        } catch (error) {
          options.onError?.(error instanceof Error ? error : new Error(String(error)));
        } finally {
          if (message.uid) options.store.write({ uidValidity: String(mailbox.uidValidity), lastUid: message.uid });
        }
      }
    } finally {
      lock.release();
    }
    return delivered;
  };

  const attachIdle = (): void => {
    if (!client) return;
    (client as unknown as import("node:events").EventEmitter).removeAllListeners("exists");
    client.on("exists", () => {
      void deliverNew().catch((error) => options.onError?.(error instanceof Error ? error : new Error(String(error))));
    });
  };

  const ensureConnected = async (): Promise<boolean> => {
    if (!client) return false;
    if (client.usable) return true;
    try {
      await client.connect();
      if (!client.usable) return false;
      openedMailbox = await client.mailboxOpen("INBOX");
      attachIdle();
      return true;
    } catch (error) {
      options.onError?.(error instanceof Error ? error : new Error(String(error)));
      return false;
    }
  };

  return {
    async start(): Promise<void> {
      stopped = false;
      client = createClient(options.account);
      const loop = async () => {
        if (stopped) return;
        if (await ensureConnected()) {
          try { await deliverNew(); } catch (error) { options.onError?.(error instanceof Error ? error : new Error(String(error))); }
        } else {
          // 初始连接失败：进入轮询回落（不 fatal，等待网络恢复）。
          log(`email IMAP 连接失败，进入轮询回落 agent=${options.account.address}`);
        }
        if (!stopped) reconnectTimer = setTimeout(() => void loop(), idlePollFallbackMs);
      };
      const first = loop();
      await first;
    },

    async pollOnce(): Promise<number> {
      if (!(await ensureConnected())) return 0;
      return deliverNew();
    },

    async stop(): Promise<void> {
      stopped = true;
      if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; }
      if (client) {
        try { (client as unknown as import("node:events").EventEmitter).removeAllListeners("exists"); await client.logout(); }
        catch { /* best effort */ }
        client = null;
      }
    },
  };
}
